### ISSUE TITLE
Rewrite compilation to work with latest versions of PyBind11 

### ISSUE THREAD

**Issue by grace-harper-ibm** [qiskit-community/qiskit-qec#201]
### What is the expected enhancement?
Allow use of `pybind11 >2.9.1`
Currently, if compiling with `pybind11 >2.9.1`, tests will fail because they are unable to import the cpp compiled modules.

**Comment by AnnieRay97** [comment]
Importing qiskit_qec sometimes results in this error:

undefined symbol: _ZNSt15__exception_ptr13exception_ptr10_M_releaseEv

**Comment by grace-harper** [comment]
#236
