### ISSUE TITLE
Installation from git fails due to conflict in versions 

### ISSUE THREAD

**Issue by IceKhan13** [qiskit-community/qiskit-qec#211]
### Steps to reproduce the problem

```shell
pip install git+https://github.com/qiskit-community/qiskit-qec.git
```

### What is the current behavior?

<img width="1271" alt="Screen Shot 2022-06-29 at 9 01 20 AM" src="https://user-images.githubusercontent.com/8796709/176442488-2fad2550-3635-4f92-8521-713351742083.png">

### What is the expected behavior?

Package should install without errors

**Comment by grace-harper-ibm** [comment]
I saw you merged. Did that close this issue?
