### ISSUE TITLE
Incorrect qubit labelling in `RepetitionCodeCircuit`

### ISSUE THREAD

**Issue by quantumjim** [qiskit-community/qiskit-qec#233]
### Steps to reproduce the problem

```
from qiskit_qec.decoders import DecodingGraph
from qiskit_qec.circuits import RepetitionCodeCircuit

d,T = 5,0
code = RepetitionCodeCircuit(d,T,resets=True)
code.readout()
dec_graph = DecodingGraph(code)

code.string2nodes('00001')
```

yields output

```
[{'time': 0, 'qubits': [4], 'is_boundary': True, 'element': 1},
 {'time': 0, 'qubits': [3, 4], 'is_boundary': False, 'element': 3}]
```

instead of

```
[{'time': 0, 'qubits': [0], 'is_boundary': True, 'element': 0},
 {'time': 0, 'qubits': [0,1], 'is_boundary': False, 'element': 0}]
```

### What is the current behavior?

Qubit numbers are incorrectly ordered in the `string2nodes` method of `RepetitionCodeCircuit` objects.

### What is the expected behavior?

As we have now, but with reversed qubit (and possibly also element) ordering.

**Comment by grace-harper-ibm** [comment]
Hey James, 
Should gauge_ops & flip_logical be read left-to-right or right-to-left?
