### ISSUE TITLE
tox raises ModuleNotFoundError: No module named 'pybind11'

### ISSUE THREAD

**Issue by peter-janderks** [qiskit-community/qiskit-qec#236]
### Steps to reproduce the problem
typing tox in the command line

### What is the current behavior?
I get this output:

```py36 create: /home/pderks/Documents/summerschool/qec_lectures/qiskit-qec/.tox/py36
ERROR: InterpreterNotFound: python3.6
py37 create: /home/pderks/Documents/summerschool/qec_lectures/qiskit-qec/.tox/py37
ERROR: InterpreterNotFound: python3.7
Traceback (most recent call last):
  File "setup.py", line 17, in <module>
    from pybind11.setup_helpers import Pybind11Extension, build_ext
ModuleNotFoundError: No module named 'pybind11'
ERROR: invocation failed (exit code 1)
py39 create: /home/pderks/Documents/summerschool/qec_lectures/qiskit-qec/.tox/py39
ERROR: InterpreterNotFound: python3.9
Traceback (most recent call last):
  File "/home/pderks/Documents/summerschool/qec_lectures/qiskit-qec/setup.py", line 17, in <module>
    from pybind11.setup_helpers import Pybind11Extension, build_ext
ModuleNotFoundError: No module named 'pybind11'
ERROR: invocation failed (exit code 1)
Traceback (most recent call last):
  File "/home/pderks/Documents/summerschool/qec_lectures/qiskit-qec/setup.py", line 17, in <module>
    from pybind11.setup_helpers import Pybind11Extension, build_ext
ModuleNotFoundError: No module named 'pybind11'
ERROR: invocation failed (exit code 1)
______________________________________________________________________________________ summary ______________________________________________________________________________________
ERROR:  py36: InterpreterNotFound: python3.6
ERROR:  py37: InterpreterNotFound: python3.7
ERROR:   py38: InvocationError for command /home/pderks/Documents/summerschool/qec_lectures/qiskit-qec/.tox/py38/bin/python setup.py --name (exited with code 1)
ERROR:  py39: InterpreterNotFound: python3.9
ERROR:   lint: InvocationError for command /home/pderks/Documents/summerschool/qec_lectures/qiskit-qec/.tox/lint/bin/python setup.py --name (exited with code 1)
ERROR:   coverage: InvocationError for command /home/pderks/Documents/summerschool/qec_lectures/qiskit-qec/.tox/coverage/bin/python setup.py --name (exited with code 1)
```

### What is the expected behavior?

That tox runs. Please let me know if I need to share more details. Tox worked the first time I ran it and I can run pytest on all tests in this repository.

**Comment by grace-harper-ibm** [comment]
Hey Peter!
Thanks for catching this error. It looks like `pybind11` got removed from the `requirements.txt` in a recent PR.
I'm not entirely sure if this was intentional and someone was looking to replace it or if it was a mistake in a larger PR. 

If it was a mistake, my guess is no one noticed the issue since we often do development in the same conda environments, which would've had `pybind11` installed previously. 

I've opened a PR #237 . It's still running tests right now, but once it passes I'll add my coworkers to make sure I didn't miss anything.

**Comment by grace-harper-ibm** [comment]
Hey Peter, 
I made a mistake and didn't recreate the error on my machine before adding `pybind11` back to the requirements. But even in a new environment, I'm able to run tests fine installing, even without `pybind11` showing up in the `pip freeze` 

Can you let me know what OS you're working with?

**Comment by peter-janderks** [comment]
Hi Grace,
I'm working with Ubuntu 20.04.4 LTS. I just merged main into my fork and ran tox, but still get the same error.

**Comment by grace-harper-ibm** [comment]
@peter-janderks I didn't update the `main` branch yet. You'd need to checkout `236_fix_requirements_pybind11` and run `pip install -e .` Please let me know if that fixes the tox issue.

**Comment by peter-janderks** [comment]
now it works, thanks!
