### ISSUE TITLE
Add support for code deformation

### ISSUE THREAD

**Issue by quantumjim** [qiskit-community/qiskit-qec#246]
**Describe the solution you'd proposing**
The `DecododingGraph` and decoders should be able to deal with examples of code deformation. This includes things like:
* Changing the stabilizers measured from one syndrome measurement round to the next.
* Syndrome measurements whose initial outcome may not be `0` (even without errors) and may be random.

**Additional context**

The branch [deformation-example](https://github.com/qiskit-community/qiskit-qec/tree/deformation-example) has a modified version of `RepetitionCodeCircuit` in which the code can be moved by deformation. The distance moved is given by a keyword argument `dx`. For example

    d = 3
    dx = 2
    code = RepetitionCodeCircuit(d, dx=dx, xbasis=False, resets=True)

This results in highlighted nodes even when no errors are present. For `dx=2`, for example, the output string for a logical `1` is

    '00100 0100 0100 0100 0100 0100 0100 0000'

Note that the final register of code qubits includes all `d`+`dx` used throughout the code, but only the final `d` actually get measured (the others positions in the output string are therefore `0` by default). Similarly, the registers for syndrome measurements all include all `d-1`+`dx` used throughout the code, but only a subset are actually measured in any round.

Here the syndrome result `1` comes as the code qubits used in the code move from the initial ones (initialized as `1`) into new ones (initialized as `0`). One of the two final logical readouts is then also `0` because of this, leading to the two nodes:

    [{'time': 0, 'qubits': [0], 'is_boundary': True, 'element': 0},
     {'time': 1, 'qubits': [1, 2], 'is_boundary': False, 'element': 1}]

For `dx=3`, the code fully moves away from the original set of code qubits. The final output is 

    '000000 00000 00000 00100 00100 00100 00100 00100 00100 00100 00000'

Again the `1` is the signature of moving between the domains initialized as `1` and `0`. It disappears again towards the end when the syndrome measuring it is no longer part of the code. Note that both endpoints of the code (used for logical readout) are incorrectly `0` with certainty because the whole code has moved from the original qubits. This is reflected in the nodes

        [{'time': 0, 'qubits': [0], 'is_boundary': True, 'element': 0},
         {'time': 0, 'qubits': [5], 'is_boundary': True, 'element': 1},
         {'time': 1, 'qubits': [2, 3], 'is_boundary': False, 'element': 2},
         {'time': 8, 'qubits': [2, 3], 'is_boundary': False, 'element': 2}]

For `x_basis=True`, the original qubits are initialized as $|+\rangle$ or $|-\rangle$. Moving from this to the new qubits (initialized as `0`$ will then cause random outputs.

The graph decoder needs to be able to figure this all out!

**Comment by quantumjim** [comment]
I made some background notes on what the output strings in the above actually mean.
![d=3, dx=2](https://user-images.githubusercontent.com/18051574/186609503-b5587a65-c523-405d-91fb-74e70f7763e8.jpg)
![d=3, dx=3](https://user-images.githubusercontent.com/18051574/186609539-0e030be4-24fc-4e12-831c-5de8df60ee7e.jpg)

**Comment by grace-harper-ibm** [comment]
Since we make a new classical register for every syndrome measurement, why not shrink the size of each ClassicalRegister to exactly the number of qubits measured for that round? This might make it easier for the decoder by minimizing additional, redundant information it has to work around.

**Comment by quantumjim** [comment]
After discussions with @grace-harper-ibm, it seems the best way to account for this is in the `string2nodes` method of code circuit objects, rather than in the graph decoder. So no action needed
