### ISSUE TITLE
Fibonacci Decoder

### ISSUE THREAD

**Issue by grace-harper-ibm** [qiskit-community/qiskit-qec#289]
### What is the expected behavior?
Add the Fibonacci Decoder, by Georgia Nixon & Ben Brown, seen [here](https://arxiv.org/abs/2002.11738) to qiskit-qec.

**Comment by dsvandet** [comment]
Sounds like a good idea. Did you ask Georgia for her code?

**Comment by grace-harper** [comment]
#293
