### ISSUE TITLE
Design of `antisymmetric_op` method in `base_xp_pauli`

### ISSUE THREAD

**Issue by ruihao-li** [qiskit-community/qiskit-qec#299]
https://github.com/qiskit-community/qiskit-qec/blob/6f446b6dc8f37db67cd666cf24fbe4048e4f00ef/qiskit_qec/operators/base_xp_pauli.py#L828-L846

The current implementation of `antisymmetric_op` is an instance method that returns None if the x-component of the XP operator is nonzero. However, by definition (as in Mark's paper), the antisymmetric operator is independent of an XP operator and it takes just an integer vector as input. It should not care what the x-component of the XP operator is. So I suggest we make `antisymmetric_op` a static method in this case. 

Would love to hear your thoughts on this, @dsvandet, @grace-harper-ibm.

**Comment by dsvandet** [comment]
I agree that the method is general and as you say only depends on the integer vector input. I would have a general static method that gives the exact definition of the antisymmetric operator of a given input vector. Then we could have a instance method that applies the static method in the special circumstance when the x component is 0 or we could remove the instance method and replace any use of it with the appropriate code calling the static method or returning None. The name of the general static method should be `antisymmetric_op` (well `antisymmetric_op` and `_antisymmetric_op`) as normal.

**Comment by dsvandet** [comment]
My preference would be not to have the instance method as if essentially only checks if the x component is zero and then calls the static method - i.e. unnecessarily clogging things up. If a user really wants to have such a method then they can use  their own created method.

**Comment by ruihao-li** [comment]
@dsvandet Thanks for the feedback! I also agree with your second comment. We will convert it to a static method then.
