### ISSUE TITLE
Exhaustive testing for XP operator algebras

### ISSUE THREAD

**Issue by dhruvbhq** [qiskit-community/qiskit-qec#302]
In addition to Mark's suggestion to use the use case of logical operators for CSS codes as a test case for XP operator algebras and Howell matrix code, it could be good to add more thorough test cases for this part of the code.

Most current test cases test basic functionality, calculated from the research paper for XP formalism. For one, there is a need to add tests for possible combinations of inputs of the functions (for eg, verifying `rescale_precision` for `new_precision>old_precision` as well as `new_precision<old_precision`, or, composing an `XPPauliList` of 1 operator with an `XPPauliList` containing many operators).

There is a variety of test cases for the existing `Pauli` and `PauliList` classes which could be used as a reference for writing the tests.

We can also use the values generated by Mark's XPF package to compare against the implementation in `qiskit-qec`. Since Mark's tests in `test_XPAlgebra.py` rely on random operators as inputs, we can run those tests locally with a fixed seed to generate the values to compare in a reproducible manner.

We can keep noting down more ideas about this in this thread, and pick this at some point, depending on other priorities.

**Comment by grace-harper** [comment]
Closing since QAMP has ended
