### ISSUE TITLE
Work towards unifying `codes` and `circuits`

### ISSUE THREAD

**Issue by quantumjim** [qiskit-community/qiskit-qec#330]
### What is the expected enhancement?

Create at least naive circuits (fault-tolerant against phenomenological noise only) for codes expressed abstractly in `codes`.

Will be worked in in branch [code-circuit-builder](https://github.com/qiskit-community/qiskit-qec/tree/code-circuit-builder).

Some additional ideas are [here](https://gist.github.com/quantumjim/52152cf29c88a4a052575d8af5307a87).

**Comment by grace-harper** [comment]
#328 Hey James does #328 finish this issue for you?

**Comment by quantumjim** [comment]
It's a step in the right direction, but not closed yet.
