### ISSUE TITLE
UnionFindDecoder enters infinte loop for specific real world strings

### ISSUE THREAD

**Issue by milanliepelt** [qiskit-community/qiskit-qec#352]
I tried to use the UnionFindDecoder to decode some counts which were created with the 
ARC circuit on real devices. For some strings it worked, or others it got stuck in an infinite loop. 
 For this example, the syndrome strings come from ibm_geneva. 
Yes, those strings are very messy, and definitely contain more than only Pauli noise. 

### Steps to reproduce the problem

          from qiskit_qec.circuits.repetition_code import ArcCircuit
          from qiskit_qec.decoders.hdrg_decoders import UnionFindDecoder
          from qiskit_qec.decoders.decoding_graph import DecodingGraph
          from time import time, sleep
          
          
          # First the basic setup to run a real-world strings
          links = [(1, 4, 7), (7, 10, 12), (12, 15, 18), (18, 21, 23)]
          T = 2
          basis = 'xz'
          resets = False
          color = {1: 0, 7: 1, 12: 0, 18: 1, 23: 0, 25: 1, 19: 0, 14: 1, 8: 0, 3: 1}
          schedule = [[[1, 4], [7, 10], [12, 15], [18, 21]], [[7, 4], [12, 10], [18, 15], [23, 21]]]
          code = ArcCircuit(links, T, basis, resets=resets, color=color, schedule=schedule)
          dec_graph = DecodingGraph(code, brute=True)
          decoder = UnionFindDecoder(code, decoding_graph=dec_graph)
          
          # now follows an example string from a dataset coming from ibm_geneva from march 24th
          # those are real-world strings, where not only pauli noise strike. More often we face readout errors
          # and other weird coherent errors. First an example that works. (even though, it corrects wrongly) 
          # But with those strings we have no big expectations anyway.
          good_string = "01011 0010 0110"
          t = time()
          working_outcome = decoder.process(good_string)
          print("working outcome {} in {}s".format("".join([str(s) for s in working_outcome]), time() - t))
          print("sleep for some seconds to appreciate the outcome, before we enter infinite loop.")
          sleep(3)
          
          # this string is from the same dataset from ibm_geneva, but this one puts the decoder in an infinite loop
          # at:      while self.odd_cluster_roots:
          #             self._grow_and_merge_clusters()
          error_string = "01011 0110 0111"
          t = time()
          stuck_outcome = decoder.process(error_string)
          print("This is a message we never gonna see, unless the error is fixed :) outcome: {} in {}s".format("".join([str(s) for s in stuck_outcome]), time() - t))

### What is the current behavior?
The decoder gets stuck with this second string. It enters an infinite loop, where the clusters can not grow any bigger, but also somehow don't get merged. 

### What is the expected behavior?
The decoder manages to correct those messy strings, or gives up by not correcting it. At least, it should not enter an infinite loop to block the decoding of the other 3999 of those strings.

**Comment by quantumjim** [comment]
This is being worked in in [this branch](https://github.com/qiskit-community/qiskit-qec/tree/352-uf-for-arc), where the infinite loop has been fixed. However, bad things are still happening.

For example, running the following

```
from qiskit_qec.circuits import ArcCircuit
from qiskit_qec.decoders import DecodingGraph
from qiskit_qec.decoders.hdrg_decoders import UnionFindDecoder

links = [(0, 5, 1), (1, 6, 2), (2, 7, 3), (3, 8, 4)]
code = ArcCircuit(links, 2, basis='xz', resets=False)
dec_graph = DecodingGraph(code, brute=True)
decoder = UnionFindDecoder(code, decoding_graph=dec_graph)

print('The error string')
error_string = "01011 0110 0111"
print(error_string)
print('corresponds to the nodes with the following indices')
print([ decoder.graph.nodes().index(node) for node in code.string2nodes(error_string, all_logicals=True)])
print('which cluster as follows')
decoder.cluster(code.string2nodes(error_string, all_logicals=True))
```

*sometimes* results in the output

```
The error string
01011 0110 0111
corresponds to the nodes with the following indices
[0, 9, 6, 3, 1, 7, 4, 13, 12, 11, 10]
which cluster as follows
[([0, 1, 2, 3, 4, 5, 6, 7], [0, 1, 3, 4, 6, 7]),
 ([12, 13], [12, 13]),
 ([10, 11], [10, 11])]
```

Note that the clusters include node 5, which did not appear in the original set of nodes. **Where did it come from?**

Also, the same code sometimes gives other results, such as

```
The error string
01011 0110 0111
corresponds to the nodes with the following indices
[0, 8, 5, 3, 1, 6, 4, 13, 12, 11, 10]
which cluster as follows
Note: The following odd roots could not be removed
[6]
[([0, 1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 12, 13],
  [0, 1, 3, 4, 5, 6, 10, 11, 12, 13])]
```

this is an instance that would have had an infinite loop.

**Comment by quantumjim** [comment]
It looks like some of what I mentioned above is also true for a corresponding standard repetition code. For example

```
from qiskit_qec.circuits import RepetitionCodeCircuit
from qiskit_qec.decoders import DecodingGraph
from qiskit_qec.decoders.hdrg_decoders import UnionFindDecoder

rep_code = RepetitionCodeCircuit(5, 2, resets=False)
rep_dec_graph = DecodingGraph(rep_code, brute=True)
rep_decoder = UnionFindDecoder(rep_code, decoding_graph=rep_dec_graph)

print('The error string')
error_string = "01011 0110 0111"
print(error_string)
print('corresponds to the nodes with the following indices')
nodes = rep_code.string2nodes(error_string, all_logicals=True)
print([ rep_decoder.graph.nodes().index(node) for node in nodes])
print('which cluster as follows')
rep_decoder.cluster(nodes)
```

gives us

```
The error string
01011 0110 0111
corresponds to the nodes with the following indices
[2, 9, 0, 3, 5, 4, 6, 10, 11, 12, 13]
which cluster as follows
[([0, 1, 2, 3, 4, 5, 6], [0, 2, 3, 4, 5, 6]),
 ([10, 11], [10, 11]),
 ([12, 13], [12, 13])]
```

Where did node 9 go? And where did node 1 come from?

**Comment by quantumjim** [comment]
@tommasopeduzzi Do you have any insights on the first thing noted above?

**Comment by quantumjim** [comment]
I've got a lead that I'm following. The output for the actual problem is

```
The error string
01011 0110 0111
corresponds to the nodes with the following indices
[0, 8, 5, 3, 1, 7, 4, 13, 12, 11, 10]
which cluster as follows
Note: The following odd roots could not be removed
[7]
[([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13],
  [0, 1, 3, 4, 5, 7, 8, 10, 11, 12, 13])]
```

So I took those nodes and ran check nodes on them

```
nodes = [decoder.decoding_graph.graph.nodes()[n] for n in [0, 1, 3, 4, 5, 7, 8, 10, 11, 12, 13]]

neutral, boundary, num = code.check_nodes(nodes)

print(neutral, decoder.decoding_graph.graph.nodes().index(boundary[0]), num)
```
This reveals that `neutral=True` with the boundary node `8` required. But since node `8` is included in the input, there's no reason for it to be listed in the boundary. This seems to be an issue in `check_nodes` for ARCs.
