### ISSUE TITLE
Upgrade to QiskitAerSimulator 

### ISSUE THREAD

**Issue by grace-harper** [qiskit-community/qiskit-qec#367]
### Steps to reproduce the problem
Run Tests

### What is the current behavior?
 ```PendingDeprecationWarning: The `QasmSimulator` backend will be deprecated in the future. It has been superseded by the `AerSimulator` backend.
  warn('The `QasmSimulator` backend will be deprecated```

### What is the expected behavior?
We should be using the more current simulator version

**Comment by robotAstray** [comment]
Hello @grace-harper, I will work on this, thank you

**Comment by grace-harper** [comment]
Handled in #378 by @robotAstray. Thank you!
