### ISSUE TITLE
Stop depending on Circuit Metadata | Upgrade Qiskit-Terra Dependency Cap the Qiskit-Terra version

### ISSUE THREAD

**Issue by grace-harper** [qiskit-community/qiskit-qec#369]
### What is the expected behavior?
Running tests yields:

``` 
Test the error rates using some repetition codes. ... python3.9/site-packages/qiskit_aer/backends/aerbackend.py:463: DeprecationWarning: Setting metadata to None was deprecated in Terra 0.24.0 and this ability will be removed in a future release. Instead, set metadata to an empty dictionary.
  circ.metadata = metadata
```

In order to upgrade to Terra 0.24.0, we need to be sure that the metadata isn't necessary for our code to run properly. If it is, we need to create a workaround.

**Comment by quantumjim** [comment]
Is there any more info on this issue? I don't see this test failure (even when I remove the cap), and I don't know what dependance on metadata is causing it.

**Comment by grace-harper** [comment]
Same as #365 issue. Handled in PR: #385
