### ISSUE TITLE
ValueError when Constructing PauliList from Pauli data

### ISSUE THREAD

**Issue by robotAstray** [qiskit-community/qiskit-qec#380]
### Steps to reproduce the problem

1. Install the `qiskit-qec` as per instruction
2. Navigate to the repository: cd `qiskit-qec`
3. Run the test suite: `tox -epy311 -- -n ./test/operators/test_pauli_list.py `

### What is the expected behavior?

The test suite should run without errors, and the  test cases should pass successfully.

### Actual Behavior:

During the execution of `tox -epy311 -- -n ./test/operators/test_pauli_list.py `  there are several errors of the same type. An error is raised with the following traceback:

```
DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated...
...
ValueError: setting an array element with a sequence.
```

### Additional Information:

- The error occurs specifically within the `_from_paulis` method in the `pauli_list.py` file.
- The error seems to be related to how the `_phase_exp` attribute of the `Pauli` object is being used within the loop.
- It appears that `_phase_exp` might be an array-like object, and the error is caused when trying to assign its values to the `phase_exp` NumPy array.
- it is attempting to assign a sequence (e.g.  a list or an array) to an individual element within a NumPy array.  

### Environment:

Python version: `3.11`
NumPy version: `1.25.2`
`qiskit-qec` version: latest

**Comment by grace-harper** [comment]
Thank you!
