### ISSUE TITLE
Pauli to_label returning non-scalar phases

### ISSUE THREAD

**Issue by grace-harper** [qiskit-community/qiskit-qec#386]
### Background
In the `src/qiskit_qec/operators/pauli.py` file, in the `Pauli` class, the `to_instruction` method assumes that the `phase_exp` returned by `self.to_label` is a numpy array not a scalar. 

So, `to_instruction` extracts the phase scalar from `phase_exp` by doing `phase_exp[0]`  in the lines 
`if not phase_exp[0]:` 
and  
`circuit.global_phase = -phase_exp[0] * pi / 2`  
(This is critical for the tests passing.) 
However, as described below, the `to_label` method actually should not be returning `phase_exp` as a numpy array.

We need to understand why `to_label` is returning `phase_exp` as a numpy array. 

### More information 
_Originally posted by @dsvandet in https://github.com/qiskit-community/qiskit-qec/pull/385#discussion_r1328925417_

1. self._to_label  suggests that it returns Union[str,List[str]] which is not quite correct. Depending on if return_phase is set it may return Tuple[Union[str,List[str]],Any] where the Any is the phase exponent. The output should be consistent and so it should always return a tuple and phase_exp - this is a little extra work but better to be consistent.

2. The default for to_label is to have squeeze=True  and so it should be returning a scalar and not a numpy array. Thus this event should not happen as this is on a single Pauli. So the error might actually be in the symplectic2str method if somehow you need this added line.

**Comment by dsvandet** [comment]
Turns out not to be an issue. The BasePauli methods are all vectorized and the `squeeze` option allows the methods to not return a list consisting of a single item. This occurs in to_instruction when the single Pauli is returned instead of a list containing a single Pauli. The _phase_exp for that Pauli will not be effected and so will return as a numpy array!

**Comment by dsvandet** [comment]
Closing issue.
