### ISSUE TITLE
qiskit_qec.linear.symplectic.def _symplectic_product_vv_boolean gives wrong results

### ISSUE THREAD

**Issue by kaiott** [qiskit-community/qiskit-qec#431]
### Steps to reproduce the problem
```
import numpy as np
from qiskit_qec.linear.symplectic import _symplectic_product_vv_boolean

a = np.array([1,0,0,0,1,1,1,0,1,0], dtype=np.bool_)
b = np.array([1,1,1,1,0,0,1,0,1,1], dtype=np.bool_)
_symplectic_product_vv_boolean(a, b, 5)
```

### What is the current behavior?
Returns `1`

### What is the expected behavior?
The function should return `0`, which is the actual symplectic product of the two vectors.
This example is actually the example in the docstring. 

Note: Within qiskit_qec this function is never used, as in `symplectic_product` the input arrays are always converted to dtype numpy.int8.

**Comment by drewvandeth** [comment]
Thanks @kaiott This is definitely and a rather simple fix:

 `r += vec1[i] & vec2[n + i] ^ vec1[n + i] & vec2[i]`
 
 should be
 
` r ^= vec1[i] & vec2[n + i] ^ vec1[n + i] & vec2[i]`

**Comment by drewvandeth** [comment]
I will include this fix in a PR that I am pushing through now.
PR #437
